name: Python and Playwright Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  
  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      -       - name: Install Playwright dependencies
        run: cd playwright-tests && npm install

      - name: Install only Chromium browser
        run: cd playwright-tests && npx playwright install chromium

      - name: Run Playwright tests
        run: cd playwright-tests && npx playwright test
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}

